llm:
  provider: openai
  api_key: ${OPENAI_API_KEY}
  model_name: gpt-3.5-turbo
  temperature: 0.7

embeddings:
  provider: openai
  model_name: text-embedding-3-small
  api_key: ${OPENAI_API_KEY}

repos:
  - name: Treinamento Modern Data Stack
    path: /Users/tiagonpsilva/code/treinamento-modern-data-stack-01
    enabled: true

prompt:
  path: ./prompts/prompt-base.txt
  description: Agente especialista em Modern Data Stack 